export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN'
export type FETCH_USER_BEGIN = typeof FETCH_USER_BEGIN

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export type FETCH_USER_SUCCESS = typeof FETCH_USER_SUCCESS

export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export type FETCH_USER_FAILURE = typeof FETCH_USER_FAILURE

export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'
export type CLEAR_USER_DATA = typeof CLEAR_USER_DATA

export const SET_TEAM_MAP = 'SET_TEAM_MAP'
export type SET_TEAM_MAP = typeof SET_TEAM_MAP


export const FETCH_BOOKS_MAP_BEGIN = 'FETCH_BOOKS_MAP_BEGIN'
export type FETCH_BOOKS_MAP_BEGIN = typeof FETCH_BOOKS_MAP_BEGIN

export const FETCH_BOOKS_MAP_SUCCESS = 'FETCH_BOOKS_MAP_SUCCESS'
export type FETCH_BOOKS_MAP_SUCCESS = typeof FETCH_BOOKS_MAP_SUCCESS

export const FETCH_BOOKS_MAP_FAILURE = 'FETCH_BOOKS_MAP_FAILURE'
export type FETCH_BOOKS_MAP_FAILURE = typeof FETCH_BOOKS_MAP_FAILURE



export const SET_MODULES_MAP = 'SET_MODULES_MAP'
export type SET_MODULES_MAP = typeof SET_MODULES_MAP

export const ADD_MODULE_TO_MAP = 'ADD_MODULE_TO_MAP'
export type ADD_MODULE_TO_MAP = typeof ADD_MODULE_TO_MAP

export const REMOVE_MODULE_FROM_MAP = 'REMOVE_MODULE_FROM_MAP'
export type REMOVE_MODULE_FROM_MAP = typeof REMOVE_MODULE_FROM_MAP

export const SET_ASSIGNED_TO_ME = 'SET_ASSIGNED_TO_ME'
export type SET_ASSIGNED_TO_ME = typeof SET_ASSIGNED_TO_ME

export const SET_ASSIGNE_IN_MODULES_MAP = 'SET_ASSIGNE_IN_MODULES_MAP'
export type SET_ASSIGNE_IN_MODULES_MAP = typeof SET_ASSIGNE_IN_MODULES_MAP

export const SET_REFERENCE_TARGETS = 'SET_REFERENCE_TARGETS'
export type SET_REFERENCE_TARGETS = typeof SET_REFERENCE_TARGETS


export const PUSH_NOTIFICATION_TO_STORE = 'PUSH_NOTIFICATION_TO_STORE'
export type PUSH_NOTIFICATION_TO_STORE = typeof PUSH_NOTIFICATION_TO_STORE

export const MARK_NOTIFICATION_AS_READ = 'MARK_NOTIFICATION_AS_READ'
export type MARK_NOTIFICATION_AS_READ = typeof MARK_NOTIFICATION_AS_READ

export const MARK_NOTIFICATION_AS_UNREAD = 'MARK_NOTIFICATION_AS_UNREAD'
export type MARK_NOTIFICATION_AS_UNREAD = typeof MARK_NOTIFICATION_AS_UNREAD

export const FETCH_NOTIFICATIONS_BEGIN = 'FETCH_NOTIFICATIONS_BEGIN'
export type FETCH_NOTIFICATIONS_BEGIN = typeof FETCH_NOTIFICATIONS_BEGIN

export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export type FETCH_NOTIFICATIONS_SUCCESS = typeof FETCH_NOTIFICATIONS_SUCCESS

export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE'
export type FETCH_NOTIFICATIONS_FAILURE = typeof FETCH_NOTIFICATIONS_FAILURE



export const PUSH_ALERT = 'PUSH_ALERT'
export type PUSH_ALERT = typeof PUSH_ALERT

export const REMOVE_ALERT = 'REMOVE_ALERT'
export type REMOVE_ALERT = typeof REMOVE_ALERT



export const SET_CONVERSATION = 'SET_CONVERSATION'
export type SET_CONVERSATION = typeof SET_CONVERSATION

export const PUSH_MSG_TO_CONVERSATION = 'PUSH_MSG_TO_CONVERSATION'
export type PUSH_MSG_TO_CONVERSATION = typeof PUSH_MSG_TO_CONVERSATION


export const SET_LOCALE = 'SET_LOCALE'
export type SET_LOCALE = typeof SET_LOCALE

export const SET_AVAILABLE_LOCALES = 'SET_AVAILABLE_LOCALES'
export type SET_AVAILABLE_LOCALES = typeof SET_AVAILABLE_LOCALES

export const SET_ROLES = 'SET_ROLES'
export type SET_ROLES = typeof SET_ROLES

export const SET_PROCESSES = 'SET_PROCESSES'
export type SET_PROCESSES = typeof SET_PROCESSES
