export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN'
export type FETCH_USER_BEGIN = typeof FETCH_USER_BEGIN

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export type FETCH_USER_SUCCESS = typeof FETCH_USER_SUCCESS

export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export type FETCH_USER_FAILURE = typeof FETCH_USER_FAILURE

export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'
export type CLEAR_USER_DATA = typeof CLEAR_USER_DATA



export const FETCH_DASHBOARD_BEGIN = 'FETCH_DASHBOARD_BEGIN'
export type FETCH_DASHBOARD_BEGIN = typeof FETCH_DASHBOARD_BEGIN

export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS'
export type FETCH_DASHBOARD_SUCCESS = typeof FETCH_DASHBOARD_SUCCESS 

export const FETCH_DASHBOARD_FAILURE = 'FETCH_DASHBOARD_FAILURE'
export type FETCH_DASHBOARD_FAILURE = typeof FETCH_DASHBOARD_FAILURE 
